### ISSUE TITLE
Bulk Username Checker

### ISSUE THREAD

**Issue by crimvirt** [TufayelLUS/Twitter-Name-Availability-Lookup#1]
I don't how do I check a TXT files that have a lot of usernames separated with whitespace. I typed in the terminal: 
python c:/Users/user/Desktop/Twitter-UserName-Availability-Lookup-master/Twitter-UserName-Availability-Lookup-master/lookup.py -li c:/Users/user/Desktop/Twitter-UserName-Availability-Lookup-master/Twitter-UserName-Availability-Lookup-master/list 1.txt

But the output is:
You are looking for 'c:/Users/user/Desktop/Twitter-UserName-Availability-Lookup-master/Twitter-UserName-Availability-Lookup-master/list'
Username is available
*****************
For debug output:
*****************
{'data': {}, 'errors': [{'message': 'Not found', 'path': ['user'], 'locations': [{'line': 126, 'column': 3}], 'source': 'Server', 'code': 50, 'kind': 'NonFatal', 'extensions': {'source': 'Server', 'code': 50, 'kind': 'NonFatal'}}]}
******************************

Help me how do I properly use this. Thanks

**Comment by TufayelLUS** [comment]
Hi, thank you for opening the issue. I can see that you are running the command with the wrong parameters.
<code>python c:/Users/user/Desktop/Twitter-UserName-Availability-Lookup-master/Twitter-UserName-Availability-Lookup-master/lookup.py -l c:/Users/user/Desktop/Twitter-UserName-Availability-Lookup-master/Twitter-UserName-Availability-Lookup-master/list 1.txt</code>
It should work fine.

**Comment by TufayelLUS** [comment]
If your problem still persists even after running the above correct command, please feel free to add more comments to this issue. Thank you very much. I am closing this for now.
